/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RazelsPackage;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JF_Login extends javax.swing.JFrame {

    /**
     * Creates new form JF_Login
     */
    public JF_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Login = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        edt_Username = new javax.swing.JTextField();
        lbl_Password = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        edt_Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 1000));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("form_Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 709));
        setType(java.awt.Window.Type.POPUP);

        pnl_Login.setBackground(new java.awt.Color(153, 0, 153));
        pnl_Login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Segoe UI Black", 1, 12))); // NOI18N
        pnl_Login.setPreferredSize(new java.awt.Dimension(850, 500));

        lbl_Name.setFont(new java.awt.Font("Tahoma", 3, 80)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(242, 242, 242));
        lbl_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Name.setText("Razels");

        edt_Username.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        edt_Username.setName("edt_Username"); // NOI18N
        edt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_UsernameActionPerformed(evt);
            }
        });
        edt_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edt_UsernameKeyPressed(evt);
            }
        });

        lbl_Password.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 25)); // NOI18N
        lbl_Password.setText("Password:");
        lbl_Password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Password.setName("lbl_Password"); // NOI18N

        lbl_Username.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 25)); // NOI18N
        lbl_Username.setText("Username:");
        lbl_Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_Login.setBackground(new java.awt.Color(0, 0, 0));
        btn_Login.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Sign in");
        btn_Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Login.setBorderPainted(false);
        btn_Login.setName("btn_Login"); // NOI18N
        btn_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LoginMouseClicked(evt);
            }
        });
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        edt_Password.setToolTipText("");
        edt_Password.setName("edt_Password"); // NOI18N
        edt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edt_PasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LoginLayout = new javax.swing.GroupLayout(pnl_Login);
        pnl_Login.setLayout(pnl_LoginLayout);
        pnl_LoginLayout.setHorizontalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 269, Short.MAX_VALUE))
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginLayout.createSequentialGroup()
                        .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(edt_Password)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginLayout.createSequentialGroup()
                        .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_LoginLayout.setVerticalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(edt_Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_UsernameActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
    
        String username,password;
        btn_Login.setEnabled(false);
        new JF_Login().setVisible(false);
        username = edt_Username.getText();
        password = edt_Password.getText();
        EmployeeDAO emp = new EmployeeDAO();
        Boolean bAuth = emp.authEmployee(password,username);
        //System.out.println(bAuth);
        //bAuth=true;
        
      
        if (username.isEmpty() || password.isEmpty() || username.isBlank() || password.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Login Credentials", "ERROR", HEIGHT);
            edt_Username.setText("");
            edt_Password.setText("");
            btn_Login.setEnabled(true);
        }
        
        else if(bAuth==false){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Login Credentials", "ERROR", HEIGHT);
            edt_Username.setText("");
            edt_Password.setText("");
            btn_Login.setEnabled(true);
        }
        
        else{
            btn_Login.setEnabled(false);
            new JF_Manager_Home().setVisible(true);
            new JF_Login().dispose();
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_LoginMouseClicked

    private void edt_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt_UsernameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c)) || (Character.isISOControl(c)) || (Character.isWhitespace(c))  ){
            edt_Username.setEditable(true);
        }
        else{
            edt_Username.setEditable(false);
        }
    }//GEN-LAST:event_edt_UsernameKeyPressed

    private void edt_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt_PasswordKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((evt.getKeyChar() >= '0') && (evt.getKeyChar() <= '9')){
            edt_Password.setEditable(true);
        }
        else if ((evt.getExtendedKeyCode()== KeyEvent.VK_DELETE) || (evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE)){
            edt_Password.setEditable(true);
        }
        else {
            edt_Password.setEditable(false);
        }
    }//GEN-LAST:event_edt_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JPasswordField edt_Password;
    private javax.swing.JTextField edt_Username;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JPanel pnl_Login;
    // End of variables declaration//GEN-END:variables
}
